name: Docker Build Test Using Action

on:
  workflow_dispatch:

jobs:
  something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.JF_USERNAME }}
          password: ${{ secrets.JF_PASSWORD }}
          registry: tomjfrog.jfrog.io

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Format Build Tag
        id: format-build-tag
        shell: bash
        run: echo "build-tag=b${GITHUB_RUN_NUMBER}-${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tomjfrog.jfrog.io/docker-github-actions/ubuntu
          tags: |
            type=sha,format=long,prefix=
            type=raw,value=${{ steps.format-build-tag.outputs.build-tag }}
          labels: |
            github.actions.runner.run.id=${{ github.run_id }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true